# Generated by Django 4.1.5 on 2023-08-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.TextField(default=0, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(verbose_name='Phone Number'),
        ),
    ]
