# Generated by Django 4.1.5 on 2023-08-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_employee_location_alter_employee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='location',
        ),
        migrations.AlterField(
            model_name='employee',
            name='bouns',
            field=models.IntegerField(default=0, verbose_name='Bouns'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(default=0, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='Salary'),
        ),
    ]
